### ISSUE TITLE
ValueError: The numbers of items and labels differ: |x| = 10, |y| = 6

### ISSUE THREAD

**Issue by ztz1989** [fukuda-lab/LogDTL#1]
Dear experts of LogDTL,

Thanks a lot for contributing this wonderful framework to the community. I am really interested in this work. However, when I tried to run the crf python script today, I got this ValueError and it seems the size of the training data was messed up somewhere. Could you help with this issue? Thanks in advance!

**Comment by thieu1995** [comment]
Hi @ztz1989 ,

Sorry for the late reply. We have updated this issue, you can try it again and give us feedbacks. Thanks

**Comment by ztz1989** [comment]
Thanks a lot @thieu1995, I'll give it a try later. 

Best regards,
Tianzhu
